name: flutter_neat_state
description: Some utilities to make work with a neat_state package in Flutter more convenient
version: 0.0.2
homepage: https://github.com/sla-000/flutter_neat_state

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  neat_state: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
